alter session set deferred_segment_creation=false;

DROP TABLE ACTIVITY;
DROP TABLE BILL;
DROP TABLE COUNTRIES;
DROP TABLE DEPARTMENTS;
DROP TABLE EMPLOYEES;
DROP TABLE JOBS;
DROP TABLE LOCATIONS;
DROP TABLE REGIONS;
DROP TABLE FILMREVIEW;

CREATE TABLE ACTIVITY (
  ACTIVITY_NO    NUMBER(10,0)  NOT NULL, 
  ACTIVITY_NAME  VARCHAR2(200) NOT NULL, 
  ACTIVITY_DESC  VARCHAR2(500) NOT NULL,
  BACKSTAGE_NO   NUMBER(10,0)  NOT NULL, 
  CREATED_AT     Date		   NOT NULL, 
  UPDATED_AT     Date          NOT NULL, 
  ACTIVE         Number(1,0)   ,
  IMG_PATH       Varchar2(50)  NOT NULL,
  ACTIVITY_URL   Varchar2(200) NOT NULL);


Insert into ACTIVITY (ACTIVITY_NO,ACTIVITY_NAME,ACTIVITY_DESC,BACKSTAGE_NO,CREATED_AT,UPDATED_AT,ACTIVE,IMG_PATH,ACTIVITY_URL) 
values (1,'玃綪','铬加玃綪',1,TO_DATE('2018-09-01','YYYY-MM-DD'),TO_DATE('2018-09-02','YYYY-MM-DD'),1,'C:\desktop','D:\desktop');



CREATE TABLE ANNOUNCEMENT (
  ANC_NO         NUMBER(10,0)  NOT NULL, 
  ANC_CON        VARCHAR2(500) NOT NULL, 
  BACKSTAGE_NO   NUMBER(10,0)  NOT NULL,
  CREATED_AT     Date		   NOT NULL, 
  UPDATED_AT     Date          NOT NULL, 
  ACTIVE         Number(1,0)   );
  
Insert into ANNOUNCEMENT (ANC_NO,ANC_CON,BACKSTAGE_NO,CREATED_AT,UPDATED_AT,ACTIVE) 
values (1,'玃綪',1,TO_DATE('2018-09-01','YYYY-MM-DD'),TO_DATE('2018-09-02','YYYY-MM-DD'),1);

CREATE TABLE BACKSTAGE_ROLE (
  BR_NO          NUMBER(10,0)  NOT NULL, 
  BR_NAME        VARCHAR2(100) ) ;
 
  
Insert into BACKSTAGE_ROLE (BR_NO,BR_NAME) 
values (1,'à︹嘿');

CREATE TABLE FILMREVIEW (
  MFR_NO         NUMBER(10,0)  NOT NULL, 
  MOVIE_NO       NUMBER(10,0) NOT NULL, 
  CREATED_AT     Date		   NOT NULL, 
  UPDATED_AT     Date          NOT NULL, 
  CONTENT        CLOB          NOT NULL,
  EVALUATION     NUMBER(2,1)   ,
  TITLE          Varchar2(300) NOT NULL,
  SOURCE         Varchar2(60)  , 
  URL            Varchar2(200) , 
  MEM_NO         Number(10,0)  ,
  AUTHOR         Varchar2(60)  ,
  ACTIVE         Number(1,0)   );


Insert into FILMREVIEW (MFR_NO,MOVIE_NO,CREATED_AT,UPDATED_AT,CONTENT,EVALUATION,TITLE,SOURCE,URL,MEM_NO,AUTHOR,ACTIVE) 
values (1,1,TO_DATE('2018-09-01','YYYY-MM-DD'),TO_DATE('2018-09-02','YYYY-MM-DD'),'铬加玃綪',5.0,'铬加玃綪2','铬加玃綪3','http:\\re@13.com',1,'',1);

CREATE TABLE FILMREVIEW_MSG (
  FRM_NO         NUMBER(10,0)  NOT NULL, 
  MFR_NO         NUMBER(10,0)  NOT NULL, 
  MEM_NO         NUMBER(10,0)  NOT NULL,
  CREATED_AT     Date		   NOT NULL, 
  UPDATED_AT     Date          NOT NULL, 
  CONTENT        Varchar2(600) NOT NULL,
  PARENT_ID      NUMBER(10,0)  );
  
Insert into FILMREVIEW_MSG (FRM_NO,MFR_NO,MEM_NO,CREATED_AT,UPDATED_AT,CONTENT,PARENT_ID) 
values (1,1,1,TO_DATE('2018-09-01','YYYY-MM-DD'),TO_DATE('2018-09-02','YYYY-MM-DD'),'铬加玃綪',1);

CREATE TABLE REPORT_FILMREVIEW_MSG (
  RFM_NO         NUMBER(10,0)  NOT NULL, 
  MESSAGE_NO     NUMBER(10,0)  NOT NULL, 
  MEM_NO         NUMBER(10,0)  NOT NULL,
  STATE          NUMBER(1,0)   , 
  CONTENT        Varchar2(600) NOT NULL );
  
Insert into REPORT_FILMREVIEW_MSG (RFM_NO,MESSAGE_NO,MEM_NO,STATE,CONTENT) 
values (1,1,1,1,'铬加玃綪');




commit;